bases:
  - ../../base
patches:
  - healthcheck_patch.yaml
  - memorylimit_patch.yaml
  - replicas_patch.yaml
namePrefix: production-
configMapGenerator:
  - name: demo-configmap
    files:
      - application.properties
