apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    name: staging-db
    app: staging-db
spec:
  containers:
    - name: mysql
      image: mysql:latest
      initContainers:
        image: mysql:latest
        command:
          - mysql_ssl_rsa_setup
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: admin
        - name: MYSQL_DATABASE
          value: db_example
      ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
      volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
  volumes:
    - name: mysql-storage
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: prod-db
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: staging-db
