kind: Deployment
apiVersion: apps/v1
metadata:
  name: ss-test
  namespace: secret-test
  labels:
    app: ss-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ss-test
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ss-test
      annotations:
    spec:
      containers:
        - name: ss-test
          image: registry.redhat.io/ubi8
          command:
            - sleep
            - "86400"
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          volumeMounts:
            - name: secrets
              mountPath: /secrets
      volumes:
        - name: secrets
          secret:
            secretName: ss-secret
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
