kind: Deployment
apiVersion: apps/v1
metadata:
  name: vault-test
  namespace: secret-test
  labels:
    app: vault-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-test
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vault-test
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-issues-config.txt: kv/secret/test/config
        vault.hashicorp.com/role: vault-user-test
    spec:
      containers:
        - name: vault-test
          image: registry.redhat.io/ubi8
          command:
            - sleep
            - "86400"
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: vault-user
      serviceAccount: vault-user
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
